spring:
  datasource:
    url: jdbc:mysql://localhost:3366/usersdb
    username: root
    password: 13.5.45.8.62
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true


